spring.application.name=demo
spring.security.user.name=user
spring.security.user.password=password
spring.app.jwtSecret=ThisIsAVeryStrongJwtSecretKeyForSpringBootProject123456
spring.app.jwtExpirationMs=86400000

#GitHub oauth configuration
spring.security.oauth2.client.registration.github.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=read:user,user:email 
  #scope defines what permissions your application is requesting from GitHub

#google oauth configuration
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/editorplatform
spring.datasource.username=abhavkushwaha
spring.datasource.password=postgres123

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

# DATABASE DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#redis config
# Redis config
spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379
spring.cache.type=redis
logging.level.org.hibernate.SQL=DEBUG

#mail verification
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false