# Production profile (Render)
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN

# Disable Redis (use in-memory cache)
spring.cache.type=simple
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

spring.data.redis.repositories.enabled=false

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
